# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: add15f68501af7685c0754d5af356659490683354fad17582e54832f3e74ad55c3b1d976ec36c4828638919434a658bf99db8ace3ab4f0002cfc6cf7af4025dd

test:
  secret_key_base: f5c13fe2fe787a97587ad0f2a187f8e4762962ee37d5e812c8e370c9b337789f901df941e24ffb4be8c52159a029de649fb543fab6052b798a58ec944fb0bf5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
